#!/bin/sh

cd $(realpath test/)

mkdir -p config/{backups,targets}
mkdir -p profile
mkdir -p runtimedir

rm -rf config/backups/*
rm -rf profile/*
rm -rf runtimedir/*

mkdir -p profile/{profile.one,profile.two}
touch profile/{profile.one,profile.two}/data

export BOR_TMPDIR=$(realpath runtimedir/)
export BOR_CONFDIR=$(realpath config/)
browser-on-ram -v -s -b "test-browser" "$(realpath profile/profile.one/)" "$(realpath profile/profile.two/)"

tree -a
cat config/backups/test-browser/targets.txt

browser-on-ram -v -u -b "test-browser"
