#!/bin/sh

bor="$(realpath $1)"

cd $(dirname $(realpath $0))

mountpoint tmpfs/bor && sudo umount tmpfs/bor

rm -rf config tmpfs share test-browser

mkdir -p config/bor
mkdir -p tmpfs/bor
mkdir -p share/bor/scripts
mkdir -p test-browser/{profile.one,cache.one}

touch test-browser/{profile.one,cache.one}/data

echo test-browser > config/bor/browsers.conf

cat <<EOT > share/bor/scripts/test-browser.sh
root=$\(realpath $\(dirname $\(realpath \$0\)\)/../../../test-browser\)

echo test profile \$root/profile.one
echo test cache \$root/cache.one
EOT

cat <<EOT > config/bor/bor.conf
# test
enable_overlay = true
resync_cache = true
EOT

sed -i -e 's/\\//g' share/bor/scripts/test-browser.sh

echo -e "SYNCING"

$bor -v -c config/bor -d share/bor -t tmpfs --sync

[[ $? -ne 0 ]] && echo "sync returned bad exit"

touch tmpfs/bor/test-browser/profile.one/data2

tree -a --noreport

echo -e "RESYNCING"

$bor -v -c config/bor -d share/bor -t tmpfs --resync

[[ $? -ne 0 ]] && echo "resync returned bad exit"

tree -a --noreport

echo -e "UNSYNCING"

$bor -v -c config/bor -d share/bor -t tmpfs --unsync

[[ $? -ne 0 ]] && echo "unsync returned bad exit"

tree -a --noreport
